### PR TITLE
Added hand Mk3 and wrist Mk2 iCub components.

### PR DESCRIPTION
**Pull request by ale-git**
Components not yet mounted on iCub have been added to automatic generation.
They are built in iCub/parts folder.

### CODE REVIEW

**Comment by ale-git** [comment]
@fiorisi

**Comment by fiorisi** [comment]
@ale-git in `icub-models` we should not commit any model. Theoretically only the [bot](https://github.com/robotology/icub-models#icub-models) that automatically generates the models should be allowed to commit.
More in detail, starting from the files contained in ` icub-model-generator`, a continous integration service generates the URDF models and commits the URDF files in ` icub-models`. You can have a look at the [dedicated script](https://github.com/robotology/icub-models-generator/blob/master/.travis.yml).

**Comment by traversaro** [comment]
Given our discussion and @fiorisi comment, I guess we can close the issue?

**Comment by traversaro** [comment]
Actually, I guess that some of the changes in CMakeLists.txt may need to be done as direct PRs, as all the content of this repo **outside** the `iCub`  directory is not automatically generated by https://github.com/robotology/icub-models-generator .

**Pull request closed without merging**
