### PR TITLE
icub-models python library: Raise a `FileNotFoundError` if the model path is not found

### PR DESCRIPTION
**Pull request by xela-95**
Instead of returning a placeholder `Path("...")` from https://github.com/robotology/icub-models/blob/468b9f7d033411dc138b877d4e229a4739ea083c/python/icub_models/icub_models.py#L32-L38 when the model name is not found I think it is more predictable and safe to raise an exception here.

### CODE REVIEW

**Comment by xela-95** [comment]
CC @traversaro

**Comment by traversaro** [comment]
I agree! Let's check what @GiulioRomualdi thinks.

**Comment by xela-95** [comment]
I think we need also to update the action versions here, like the pypi action is failing with:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```

**Comment by traversaro** [comment]
> I think we need also to update the action versions here, like the pypi action is failing with:
> 
> ```
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
> ```

Feel free to update it in this PR, thanks!

**Comment by traversaro** [comment]
(I changed the PR title to be more descriptive as it is going to be included in automatically generated changelog)

**Comment by xela-95** [comment]
I have updated the workflow actions and started using conda and miniforge instead of mamba and mambaforge as suggested in https://github.com/robotology/robotology-superbuild/pull/1653. Now also the CI is passing. Ready for review.

**Comment by traversaro** [comment]
Thanks!

**Review by traversaro — APPROVED** [review]

**Comment by xela-95** [comment]
@traversaro  can you also bump a new minor version after this PR? Thanks!

**Comment by traversaro** [comment]
Sure, I can do the bump directly in this PR. @GiulioRomualdi can you quickly check the change?

**Review by GiulioRomualdi — APPROVED** [review]

**Pull request merged**
